server:
  port: 9891
  
spring:
  application:
    name: Product Microservice

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  
  boot:
    admin:
      client:
        url:
          - http://localhost:8080    
 
logging:
  file:
    name: E:\logs\product.log
#   path: d:\logs  #spring.log   
  logback:
    rollingpolicy:
      max-file-size: 50KB
 # level:
 #   root: TRACE #by default it is INFO     
 
# actuator specific
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mongo:
      enabled: true

info:
  app:
    name: Product Microservice
    version: 1.0
    desccription: Add and retrieve product information     
      
      