server:
  port: 9891
  
spring:
  application:
    name: Product Microservice

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  
  boot:
    admin:
      client:
        url:
          - http://localhost:8080    
        